### ISSUE TITLE
1.5.3 Release checklist

### ISSUE THREAD

**Issue by pmaier1** [owncloud/contacts#608]
QA
- [ ] create testplan and test cases
- [ ] test and document in testplan. Final release "Go"

Marketing
- [x] Update info.xml (summary, description, etc.) https://github.com/owncloud/contacts/pull/607
- [x] Find screenshot/image

Build
- [x] bump version to 1.5.3
- [x] sign and build tarball
- [x] upload to marketplace

Docs
Nothing to do

Communication
- Blogpost on .org ? @lefherz
